const fs = require("fs");
const path = require("path");
require("dotenv").config();

const template = fs.readFileSync("./src/template.html", "utf8");


const distPath = path.join(__dirname, "dist");

if (!fs.existsSync(distPath)) {
    fs.mkdirSync(distPath, { recursive: true });
}

const html = template
  .replace("{{title}}", "My Static Site")
  .replace("{{header}}", "Generated by Node.js Multistage Build")
  .replace("{{buildTime}}", new Date().toISOString())
  .replace("{{version}}", process.env.APP_VERSION || "dev");

fs.writeFileSync("./dist/index.html", html);

console.log("index.html generated!");
